{% set name = "pytest-socket" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/miketheman/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6a1994c4ae29258936b88b279f539277ef8ebe529dca150324ff62b76765e873

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python
  run:
    - pytest >=6.2.5
    - python

test:
  requires:
    - pip
  imports:
    - pytest_socket
  commands:
    - pip check

about:
  home: https://github.com/miketheman/pytest-socket
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pytest Plugin to disable socket calls during tests
  description: |
    A plugin to use with Pytest to disable or restrict socket calls
    during tests to ensure network calls are prevented.

extra:
  recipe-maintainers:
    - duncanmmacleod
