{% set name = "pytest-socket" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f590593675161e1407df676f0aff9ae24ca52c19f0fb4f30df0aaf820fa32bb1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=0.12
    - pytest >=3.6.3
    - python
  run:
    - pytest >=3.6.3
    - python

test:
  requires:
    - pip
  imports:
    - pytest_socket
  commands:
    - python -m pip check

about:
  home: https://github.com/miketheman/pytest-socket
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pytest Plugin to disable socket calls during tests
  description: |
    A plugin to use with Pytest to disable or restrict socket calls
    during tests to ensure network calls are prevented.

extra:
  recipe-maintainers:
    - duncanmmacleod
