{% set name = "pytest-socket" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6480d6962b1f908f4b7c267ed4cfbc8fe27555562dec31cf9f8988fc1bf11f64

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - pytest >=3.6.3
    - python
    - setuptools
  run:
    - pytest >=3.6.3
    - python
    - setuptools

test:
  imports:
    - pytest_socket

about:
  home: https://github.com/miketheman/pytest-socket
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pytest Plugin to disable socket calls during tests
  description: |
    A plugin to use with Pytest to disable or restrict socket calls
    during tests to ensure network calls are prevented.

extra:
  recipe-maintainers:
    - duncanmmacleod
