travis:
  secure:
    BINSTAR_TOKEN: EtKf9YgPm3RSRVYwafsDtoPSD6+ZauEAqglBwj2Xk1jMsUVciTw+fy6AvFYjGA84XSqe1x9ZeRUbqYGO+FLkowNz+Rz2GZ3BWI95SVnikgxauGfO0DCqgtq+GBPLLtSPZoL2TN1BBsyJl3FOUE+o7LJztTJeyQ8hg68KO+6zS4UI60VQIWRppVFG8z1Hg5O+qxmyk0NWPiu2SKkpfrr2cKbIqA6cZvuis3NhYmslsd1B5G+7d0LbL1m1FbMGnharQWfA/uygdqicBQfWyKMXfOygv1w2qZVnhu/ujjpumyYpXEFfbwXYXJ1o0fA0Xwfl8WycZMp5X+qBKUGfxpwVa1fcMSb/vNqtAxZm4P8gDP/pvKrfs7x5mr7214V3GZPfVCal2ptGOwNpjDxX+Tll5JMwjXVJbE1kLT8FNCSIZt4EWtdnALNRB5AYwstFe1jIF4WyQxcQ6k6M4Wd3no7T7p49QsiViSQA596M4JcUOsbQ3PlTdLDmt9njok9TaUD3+i+RsnuONgULYihgsAWvCDISegrg5zwXcbaL1Zn91S67YWBWjrZsiAC28xF96GIG8rnE427R/F0EDyM+TCdUQqHu6r5rgHv+hc+BKRS8okODlaVKt0Wc3eSocGGOFJMumUwHqKseIUqIrABTY7IyKhconL6WmI1GQ6ip2fgRQWQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
