travis:
  secure:
    BINSTAR_TOKEN: C4sCS+2LiuJSpW7NvshCJKSDcPtZdVoISmWE8pJbXuNtyEkVne4MgsMMjNQHqmT5QDaVBEgwOh8lf9kczz3EqEIl91/ZCGVANYUNtCKO7xQfnhooGGqnp0ULRcahEDNYbPlS6XVSxyxdDiv7T3wY1Fjjl5/LL9J3/IB04UT5HDXGAP2xcso3jtLAxhP0BFFU/XRoT/ZwXrBXFrhnC4HfQgOi2+BDiOnmM9Mc350KbobrbVsp7tTnpjAGHMMMEdAjQk4wQDufJYYlncIYbFTpiphHaAWQxLFIIDBpJN63amsN8WgsminIKtScLPH6MkmR1WsiJUd4JfgrI6/dekwf+LRRsCVNn9QnIuUm98bj1ijvA8OWerEmlsRLD/6VvRhZnw2TFxLXBE8b6w0cajBF13009KBYqpvxSrgFBQTKm4p1J2FiOI4zlIUJRz4gOiRUxiN5za9m/Nm3hz0f2YxQqTGLbFbYofwbifnZDowYkfWpWlOwPZjP0hwDLR69A9YNxSJYmGUmXr6glxCKpJmQiP0kiLGBlOLVguikJHsxHSWaY8cy0PflmBNuEo/GfzRWS/qNZxNDCJb7uR0DwB86p9UB7uZA7Gl0hJptJ4Jf+A9XPND4Amiec0d+tSg3fJFqBbo3/q0ZQHW0XELZQ2VrQKUktRhFy2EdFa3lg4xvBAQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
